### ISSUE TITLE
Adding double-quotes around the NPM call stops it working

### ISSUE THREAD

**Issue by willdean** [BamButz/msbuild-extensions#13]
This is really a dup of #11, but I have hit the same problem myself, and I saw someone else did yesterday, and I've worked through what it is.

There are two places in the .targets file which invoke NPM, like this:

```
Command="&quot;$(NodeCli)&quot; install"
```
This gives the same result as if one went to the command line and typed

```
"npm" install
```

Unfortunately, this command (with the quotes around npm) will not work - npm/node is invoked, but fails to run, with the sort of error messages which people are reporting in #11.   I have not bothered to get to the bottom of this - presumably the double quotes cause something to fail in the npm command-line parsing process.

Anyway, for me, just changing the two places in the .targets file to remove the `&quot;` parts has made things work.

Given that the target already makes the assumption that you can just run `node -v` to check for the presence of Node somewhere on the path, it's probably safe to assume that you can also run `npm install`, at least in most normal circumstances.

I will put in a PR if it's helpful, but there probably was a reason why the `&quot;` got added, so maybe they need to stay in there but be moved somewhere else?

**Comment by BamButz** [comment]
I think you are right by checking that `node` must be in the path, `node` should also be available accordingly.

> Anyway, for me, just changing the two places in the .targets file to remove the &quot; parts has made things work.

Did you remove all instances of `&quot;`? Because of the first assumption, I'm with you that we could remove them from the npm part, but the file paths need to be quoted to support spaces in them.

If you build your project via Command Line (not Powershell or NuGet terminal) does it work with the `&quot;` in place?
Do you use VS2022? It seems to me that MS changed something in it, so that the build process is running on a different "shell".
